spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/JavaEE-combat
      username: root
      password: root
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
SECRET: ZZZCNY
